language: csharp
sudo: required
mono: none

matrix:
  include:
  - os: linux
    dist: trusty # Ubuntu 14.04
    dotnet: 2.1.200
    mono: none
    env: DOTNETCORE=1
    sudo: required

before_install:
  - chmod 777 ./runtests.sh

install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
  - export TRAVIS=1

script:
  - ./runtests.sh
